name: Get Data
on:
  schedule:
    - cron: 0 0 */2 * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/get-data-using-flat.yml
      - ./postprocessing/parse-covid-stats-data.js
      # - ./postprocessing/parse-mobility-data.js
      # - ./queries/query.sql
jobs:
  get-data:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://raw.githubusercontent.com/harsh8398/India-covid-policy/master/data/OxCGRT_IND_latest.csv
          downloaded_filename: ./raw-data/restrictions_per_state.csv
      - name: Fetch data
        uses: githubocto/flat@v2
        with:
          http_url: https://www.mohfw.gov.in/data/datanew.json
          downloaded_filename: ./raw-data/covid_stats_latest.json
          postprocess: ./postprocessing/parse-covid-stats-data.js
      # - name: Fetch data
      #   uses: githubocto/flat@v2
      #   with:
      #     sql_connstring: ${{ secrets.DB_CONNECTION_STRING }}
      #     sql_queryfile: ./queries/query.sql
      #     downloaded_filename: ./raw-data/mobility.csv
      #     postprocess: ./postprocessing/parse-mobility-data.js
